# Generated by Django 5.2 on 2025-05-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
