# Generated by Django 5.2 on 2025-06-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0003_scan_scan_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_output',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
