# Generated by Django 5.2 on 2025-07-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0004_scan_scan_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(default='Configuration Audit', max_length=100),
            preserve_default=False,
        ),
    ]
