SELECT json_build_object('3.1.2 Ensure the log destinations are set correctly', json_build_object('log_destination', current_setting('log_destination')));
SELECT json_build_object('3.1.3 Ensure the logging collector is enabled', json_build_object('logging_collector', current_setting('logging_collector')));
SELECT json_build_object('3.1.4 Ensure the log file destination directory is set correctly', json_build_object('log_directory', current_setting('log_directory')));
SELECT json_build_object('3.1.5 Ensure the filename pattern for log files is set correctly', json_build_object('log_filename', current_setting('log_filename')));
SELECT json_build_object('3.1.6 Ensure the log file permissions are set correctly', json_build_object('log_file_mode', current_setting('log_file_mode')));
SELECT json_build_object('3.1.7 Ensure ''log_truncate_on_rotation'' is enabled', json_build_object('log_truncate_on_rotation', current_setting('log_truncate_on_rotation')));
SELECT json_build_object('3.1.8 Ensure the maximum log file lifetime is set correctly', json_build_object('log_rotation_age', current_setting('log_rotation_age')));
SELECT json_build_object('3.1.9 Ensure the maximum log file size is set correctly', json_build_object('log_rotation_size', current_setting('log_rotation_size')));
SELECT json_build_object('3.1.11 Ensure syslog messages are not suppressed', json_build_object('syslog_sequence_numbers', current_setting('syslog_sequence_numbers')));
SELECT json_build_object('3.1.12 Ensure syslog messages are not lost due to size', json_build_object('syslog_split_messages', current_setting('syslog_split_messages')));
SELECT json_build_object('3.1.13 Ensure the program name for PostgreSQL syslog messages are correct', json_build_object('syslog_ident', current_setting('syslog_ident')));
SELECT json_build_object('3.1.14 Ensure the correct messages are written to the server log', json_build_object('log_min_messages', current_setting('log_min_messages')));
SELECT json_build_object('3.1.15 Ensure the correct SQL statements generating errors are recorded', json_build_object('log_min_error_statement', current_setting('log_min_error_statement')));
SELECT json_build_object('3.1.16 Ensure ''debug_print_parse'' is disabled', json_build_object('debug_print_parse', current_setting('debug_print_parse')));
SELECT json_build_object('3.1.17 Ensure ''debug_print_rewritten'' is disabled', json_build_object('debug_print_rewritten', current_setting('debug_print_rewritten')));
SELECT json_build_object('3.1.18 Ensure ''debug_print_plan'' is disabled', json_build_object('debug_print_plan', current_setting('debug_print_plan')));
SELECT json_build_object('3.1.19 Ensure ''debug_pretty_print'' is enabled', json_build_object('debug_pretty_print', current_setting('debug_pretty_print')));
SELECT json_build_object('3.1.20 Ensure ''log_connections'' is enabled', json_build_object('log_connections', current_setting('log_connections')));
SELECT json_build_object('3.1.21 Ensure ''log_disconnections'' is enabled', json_build_object('log_disconnections', current_setting('log_disconnections')));
SELECT json_build_object('3.1.22 Ensure ''log_error_verbosity'' is set correctly', json_build_object('log_error_verbosity', current_setting('log_error_verbosity')));
SELECT json_build_object('3.1.23 Ensure ''log_hostname'' is set correctly', json_build_object('log_hostname', current_setting('log_hostname')));
SELECT json_build_object('3.1.24 Ensure ''log_line_prefix'' is set correctly', json_build_object('log_line_prefix', current_setting('log_line_prefix')));
SELECT json_build_object('3.1.25 Ensure ''log_statement'' is set correctly', json_build_object('log_statement', current_setting('log_statement')));
SELECT json_build_object('3.2 Ensure the PostgreSQL Audit Extension (pgAudit) is enabled', json_build_object('shared_preload_libraries', current_setting('shared_preload_libraries')));
SELECT json_build_object('4.8 Ensure the set_user extension is installed', json_agg(t)) FROM (select * from pg_available_extensions where name = 'set_user') AS t;
SELECT json_build_object('6.2 Ensure ''backend'' runtime parameters are configured correctly', json_agg(t)) FROM (SELECT name, setting FROM pg_settings WHERE context IN ('backend','superuser-backend') ORDER BY 1) AS t;
SELECT json_build_object('6.8 Ensure TLS is enabled and configured correctly', json_build_object('ssl', current_setting('ssl')));
SELECT json_build_object('6.9 Ensure that TLSv1.3, or later, is configured', json_build_object('ssl_min_protocol_version', current_setting('ssl_min_protocol_version')));
SELECT json_build_object('6.11 Ensure the pgcrypto extension is installed and configured correctly', json_agg(t)) FROM (SELECT * FROM pg_available_extensions WHERE name='pgcrypto') AS t;
SELECT json_build_object('7.2 Ensure logging of replication commands is configured', json_build_object('log_replication_commands', current_setting('log_replication_commands')));
SELECT json_build_object('7.4 Ensure WAL archiving is configured and functional', json_agg(t)) FROM (SELECT name, setting FROM pg_settings WHERE name IN ('archive_mode','archive_command','archive_library') AND setting IS NOT NULL AND setting <> 'off' AND setting <> '(disabled)' AND setting <> '') AS t;
